package com.framework.datatypes;

public enum UserData {
	MONITOR_SETTINGS,
	SECURITY_SETTINGS,
	DEVICE_SETTINGS,
	NOTIFCATIONS,
	DAILY_REPORT,
	KEYLOG,
	SCREENSHOT,
	RECORDING,
	CAMERA_SNAPSHOT,
	GEOLOCATION,
	WEB_DATA
}
