package com.framework.constants;

public enum DataKeyValue {
	REGISTERED_ACCOUNT,
	MAX_DISK_QUOTA,
	CURRENT_DISK_QUOTA,
	REQUEST_TYPE,
	FILTER_TYPE,
	COMMAND_TYPE,
	COMMAND_PARAMETER,
	PATH,
	IP_ADDR,
	GEO_LOCATION,
	ATTACHMENT,
	DATA,
	ADDITIONAL_SITES,
	ADDITIONAL_SITES_OPERATION
}

